[package]
name = "ariadne_bridge"
version = "0.1.0"
edition = "2024"

[lib]
name = "ariadne_bridge"
path = "src/rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
ariadne = "0.5.0"
libc = "0.2.169"

