[package]
name = "ariadne_bridge"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = "z"  # Optimize for size.
strip = true
lto = true

[lib]
name = "ariadne_bridge"
path = "src/rust/lib.rs"
crate-type = ["cdylib", "staticlib"]

[dependencies]
ariadne = "0.5.0"
libc = "0.2.169"

